/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiMessage: typeof import('./components/Message/AiMessage.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChatBottom: typeof import('./components/Chat/ChatBottom/ChatBottom.vue')['default']
    ChatContainer: typeof import('./components/Ui/Containers/ChatContainer.vue')['default']
    ChatMiddle: typeof import('./components/Chat/ChatMiddle/ChatMiddle.vue')['default']
    ChatOpener: typeof import('./components/ChatOpener.vue')['default']
    ChatTop: typeof import('./components/Chat/ChatTop/ChatTop.vue')['default']
    ChatView: typeof import('./components/Chat/ChatView.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeView: typeof import('./components/HomeView.vue')['default']
    HumanMessage: typeof import('./components/Message/HumanMessage.vue')['default']
    IconButton: typeof import('./components/Ui/Buttons/IconButton.vue')['default']
    IconWrapper: typeof import('./components/Ui/Containers/IconWrapper.vue')['default']
    Message: typeof import('./components/Message/Message.vue')['default']
    OpenChatButton: typeof import('./components/OpenChatButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Widget: typeof import('./components/Widget.vue')['default']
    WidgetView: typeof import('./components/WidgetView.vue')['default']
  }
}
